// This is a generated file, do not edit!
// Generated by StyleKitSwiftExtractor, see https://github.com/colemancda/StyleKitView

import UIKit
/** PaintCode canvas name. */
public enum StyleKitCanvas: String {
case PermissionBadgeAnytime = "PermissionBadgeAnytime"
case PermissionBadgeOwner = "PermissionBadgeOwner"
case PermissionBadgeAdmin = "PermissionBadgeAdmin"
case PermissionBadgeScheduled = "PermissionBadgeScheduled"
case PunkuDoorLogo = "PunkuDoorLogo"
case SettingsTabBarIcon = "SettingsTabBarIcon"
case SettingsTabBarIconSelected = "SettingsTabBarIconSelected"
}

/** View for displaying PaintCode canvasses. */
@IBDesignable public class StyleKitView: UIView {

/** Name of the PaintCode canvas to be rendered. Raw value of StyleKitCanvas. */
@IBInspectable public var canvasName: String = "" { didSet { self.setNeedsDisplay() }}

public override func drawRect(rect: CGRect) {
if let canvas = StyleKitCanvas(rawValue: self.canvasName) {
switch canvas {
case .PermissionBadgeAnytime: StyleKit.drawPermissionBadgeAnytime(frame: self.bounds, tintColor: self.tintColor)
case .PermissionBadgeOwner: StyleKit.drawPermissionBadgeOwner(frame: self.bounds, tintColor: self.tintColor)
case .PermissionBadgeAdmin: StyleKit.drawPermissionBadgeAdmin(frame: self.bounds, tintColor: self.tintColor)
case .PermissionBadgeScheduled: StyleKit.drawPermissionBadgeScheduled(frame: self.bounds, tintColor: self.tintColor)
case .PunkuDoorLogo: StyleKit.drawPunkuDoorLogo(frame: self.bounds, tintColor: self.tintColor)
case .SettingsTabBarIcon: StyleKit.drawSettingsTabBarIcon(frame: self.bounds, tintColor: self.tintColor)
case .SettingsTabBarIconSelected: StyleKit.drawSettingsTabBarIconSelected(frame: self.bounds, tintColor: self.tintColor)
}}}
public override func prepareForInterfaceBuilder() {
if StyleKitCanvas(rawValue: self.canvasName) == nil {
self.backgroundColor = UIColor.grayColor()
 }
}}

